package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAllPropertiesEquals(Booking expected, Booking actual) {
        assertBookingAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAllUpdatablePropertiesEquals(Booking expected, Booking actual) {
        assertBookingUpdatableFieldsEquals(expected, actual);
        assertBookingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingAutoGeneratedPropertiesEquals(Booking expected, Booking actual) {
        assertThat(actual)
            .as("Verify Booking auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingUpdatableFieldsEquals(Booking expected, Booking actual) {
        assertThat(actual)
            .as("Verify Booking relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getCustomerLogin()).as("check customerLogin").isEqualTo(expected.getCustomerLogin()))
            .satisfies(a -> assertThat(a.getCustomerName()).as("check customerName").isEqualTo(expected.getCustomerName()))
            .satisfies(a -> assertThat(a.getProfessionalRef()).as("check professionalRef").isEqualTo(expected.getProfessionalRef()))
            .satisfies(a -> assertThat(a.getProfessionalLogin()).as("check professionalLogin").isEqualTo(expected.getProfessionalLogin()))
            .satisfies(a -> assertThat(a.getServiceRef()).as("check serviceRef").isEqualTo(expected.getServiceRef()))
            .satisfies(a -> assertThat(a.getServiceName()).as("check serviceName").isEqualTo(expected.getServiceName()))
            .satisfies(a -> assertThat(a.getPriceMinor()).as("check priceMinor").isEqualTo(expected.getPriceMinor()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getScheduledDate()).as("check scheduledDate").isEqualTo(expected.getScheduledDate()))
            .satisfies(a -> assertThat(a.getScheduledTime()).as("check scheduledTime").isEqualTo(expected.getScheduledTime()))
            .satisfies(a -> assertThat(a.getZoneId()).as("check zoneId").isEqualTo(expected.getZoneId()))
            .satisfies(a -> assertThat(a.getDeliveryMode()).as("check deliveryMode").isEqualTo(expected.getDeliveryMode()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCustomerNote()).as("check customerNote").isEqualTo(expected.getCustomerNote()))
            .satisfies(a -> assertThat(a.getOnBehalfOf()).as("check onBehalfOf").isEqualTo(expected.getOnBehalfOf()))
            .satisfies(a -> assertThat(a.getVisitAddress()).as("check visitAddress").isEqualTo(expected.getVisitAddress()))
            .satisfies(a -> assertThat(a.getCareSummaryShared()).as("check careSummaryShared").isEqualTo(expected.getCareSummaryShared()))
            .satisfies(a -> assertThat(a.getRaisedAt()).as("check raisedAt").isEqualTo(expected.getRaisedAt()))
            .satisfies(a -> assertThat(a.getRespondedAt()).as("check respondedAt").isEqualTo(expected.getRespondedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getCancelledAt()).as("check cancelledAt").isEqualTo(expected.getCancelledAt()))
            .satisfies(a -> assertThat(a.getCancelledBy()).as("check cancelledBy").isEqualTo(expected.getCancelledBy()))
            .satisfies(a ->
                assertThat(a.getCancellationReason()).as("check cancellationReason").isEqualTo(expected.getCancellationReason())
            )
            .satisfies(a -> assertThat(a.getLateCancellation()).as("check lateCancellation").isEqualTo(expected.getLateCancellation()))
            .satisfies(a -> assertThat(a.getReviewed()).as("check reviewed").isEqualTo(expected.getReviewed()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingUpdatableRelationshipsEquals(Booking expected, Booking actual) {
        // empty method
    }
}
