package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookingStatusChangeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusChangeAllPropertiesEquals(BookingStatusChange expected, BookingStatusChange actual) {
        assertBookingStatusChangeAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingStatusChangeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusChangeAllUpdatablePropertiesEquals(BookingStatusChange expected, BookingStatusChange actual) {
        assertBookingStatusChangeUpdatableFieldsEquals(expected, actual);
        assertBookingStatusChangeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusChangeAutoGeneratedPropertiesEquals(BookingStatusChange expected, BookingStatusChange actual) {
        assertThat(actual)
            .as("Verify BookingStatusChange auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusChangeUpdatableFieldsEquals(BookingStatusChange expected, BookingStatusChange actual) {
        assertThat(actual)
            .as("Verify BookingStatusChange relevant properties")
            .satisfies(a -> assertThat(a.getFromStatus()).as("check fromStatus").isEqualTo(expected.getFromStatus()))
            .satisfies(a -> assertThat(a.getToStatus()).as("check toStatus").isEqualTo(expected.getToStatus()))
            .satisfies(a -> assertThat(a.getActor()).as("check actor").isEqualTo(expected.getActor()))
            .satisfies(a -> assertThat(a.getOccurredAt()).as("check occurredAt").isEqualTo(expected.getOccurredAt()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingStatusChangeUpdatableRelationshipsEquals(BookingStatusChange expected, BookingStatusChange actual) {
        assertThat(actual)
            .as("Verify BookingStatusChange relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
