package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisputeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAllPropertiesEquals(Dispute expected, Dispute actual) {
        assertDisputeAutoGeneratedPropertiesEquals(expected, actual);
        assertDisputeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAllUpdatablePropertiesEquals(Dispute expected, Dispute actual) {
        assertDisputeUpdatableFieldsEquals(expected, actual);
        assertDisputeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAutoGeneratedPropertiesEquals(Dispute expected, Dispute actual) {
        assertThat(actual)
            .as("Verify Dispute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeUpdatableFieldsEquals(Dispute expected, Dispute actual) {
        assertThat(actual)
            .as("Verify Dispute relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getBookingReference()).as("check bookingReference").isEqualTo(expected.getBookingReference()))
            .satisfies(a -> assertThat(a.getRaisedBy()).as("check raisedBy").isEqualTo(expected.getRaisedBy()))
            .satisfies(a -> assertThat(a.getRaisedByLogin()).as("check raisedByLogin").isEqualTo(expected.getRaisedByLogin()))
            .satisfies(a -> assertThat(a.getProfessionalRef()).as("check professionalRef").isEqualTo(expected.getProfessionalRef()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRaisedAt()).as("check raisedAt").isEqualTo(expected.getRaisedAt()))
            .satisfies(a -> assertThat(a.getDueBy()).as("check dueBy").isEqualTo(expected.getDueBy()))
            .satisfies(a -> assertThat(a.getResolution()).as("check resolution").isEqualTo(expected.getResolution()))
            .satisfies(a -> assertThat(a.getResolvedBy()).as("check resolvedBy").isEqualTo(expected.getResolvedBy()))
            .satisfies(a -> assertThat(a.getResolvedAt()).as("check resolvedAt").isEqualTo(expected.getResolvedAt()))
            .satisfies(a -> assertThat(a.getRefundMinor()).as("check refundMinor").isEqualTo(expected.getRefundMinor()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeUpdatableRelationshipsEquals(Dispute expected, Dispute actual) {
        // empty method
    }
}
