package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisputeStatusChangeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeStatusChangeAllPropertiesEquals(DisputeStatusChange expected, DisputeStatusChange actual) {
        assertDisputeStatusChangeAutoGeneratedPropertiesEquals(expected, actual);
        assertDisputeStatusChangeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeStatusChangeAllUpdatablePropertiesEquals(DisputeStatusChange expected, DisputeStatusChange actual) {
        assertDisputeStatusChangeUpdatableFieldsEquals(expected, actual);
        assertDisputeStatusChangeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeStatusChangeAutoGeneratedPropertiesEquals(DisputeStatusChange expected, DisputeStatusChange actual) {
        assertThat(actual)
            .as("Verify DisputeStatusChange auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeStatusChangeUpdatableFieldsEquals(DisputeStatusChange expected, DisputeStatusChange actual) {
        assertThat(actual)
            .as("Verify DisputeStatusChange relevant properties")
            .satisfies(a -> assertThat(a.getFromStatus()).as("check fromStatus").isEqualTo(expected.getFromStatus()))
            .satisfies(a -> assertThat(a.getToStatus()).as("check toStatus").isEqualTo(expected.getToStatus()))
            .satisfies(a -> assertThat(a.getActor()).as("check actor").isEqualTo(expected.getActor()))
            .satisfies(a -> assertThat(a.getOccurredAt()).as("check occurredAt").isEqualTo(expected.getOccurredAt()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeStatusChangeUpdatableRelationshipsEquals(DisputeStatusChange expected, DisputeStatusChange actual) {
        assertThat(actual)
            .as("Verify DisputeStatusChange relationships")
            .satisfies(a -> assertThat(a.getDispute()).as("check dispute").isEqualTo(expected.getDispute()));
    }
}
