package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AvailabilityOverrideAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityOverrideAllPropertiesEquals(AvailabilityOverride expected, AvailabilityOverride actual) {
        assertAvailabilityOverrideAutoGeneratedPropertiesEquals(expected, actual);
        assertAvailabilityOverrideAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityOverrideAllUpdatablePropertiesEquals(AvailabilityOverride expected, AvailabilityOverride actual) {
        assertAvailabilityOverrideUpdatableFieldsEquals(expected, actual);
        assertAvailabilityOverrideUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityOverrideAutoGeneratedPropertiesEquals(AvailabilityOverride expected, AvailabilityOverride actual) {
        assertThat(actual)
            .as("Verify AvailabilityOverride auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityOverrideUpdatableFieldsEquals(AvailabilityOverride expected, AvailabilityOverride actual) {
        assertThat(actual)
            .as("Verify AvailabilityOverride relevant properties")
            .satisfies(a -> assertThat(a.getOverrideDate()).as("check overrideDate").isEqualTo(expected.getOverrideDate()))
            .satisfies(a -> assertThat(a.getClosed()).as("check closed").isEqualTo(expected.getClosed()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityOverrideUpdatableRelationshipsEquals(AvailabilityOverride expected, AvailabilityOverride actual) {
        assertThat(actual)
            .as("Verify AvailabilityOverride relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
