package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AvailabilitySlotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilitySlotAllPropertiesEquals(AvailabilitySlot expected, AvailabilitySlot actual) {
        assertAvailabilitySlotAutoGeneratedPropertiesEquals(expected, actual);
        assertAvailabilitySlotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilitySlotAllUpdatablePropertiesEquals(AvailabilitySlot expected, AvailabilitySlot actual) {
        assertAvailabilitySlotUpdatableFieldsEquals(expected, actual);
        assertAvailabilitySlotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilitySlotAutoGeneratedPropertiesEquals(AvailabilitySlot expected, AvailabilitySlot actual) {
        assertThat(actual)
            .as("Verify AvailabilitySlot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilitySlotUpdatableFieldsEquals(AvailabilitySlot expected, AvailabilitySlot actual) {
        assertThat(actual)
            .as("Verify AvailabilitySlot relevant properties")
            .satisfies(a -> assertThat(a.getSlotDate()).as("check slotDate").isEqualTo(expected.getSlotDate()))
            .satisfies(a -> assertThat(a.getSlotTime()).as("check slotTime").isEqualTo(expected.getSlotTime()))
            .satisfies(a -> assertThat(a.getTaken()).as("check taken").isEqualTo(expected.getTaken()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilitySlotUpdatableRelationshipsEquals(AvailabilitySlot expected, AvailabilitySlot actual) {
        assertThat(actual)
            .as("Verify AvailabilitySlot relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
