package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AvailabilityRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityRuleAllPropertiesEquals(AvailabilityRule expected, AvailabilityRule actual) {
        assertAvailabilityRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertAvailabilityRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityRuleAllUpdatablePropertiesEquals(AvailabilityRule expected, AvailabilityRule actual) {
        assertAvailabilityRuleUpdatableFieldsEquals(expected, actual);
        assertAvailabilityRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityRuleAutoGeneratedPropertiesEquals(AvailabilityRule expected, AvailabilityRule actual) {
        assertThat(actual)
            .as("Verify AvailabilityRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityRuleUpdatableFieldsEquals(AvailabilityRule expected, AvailabilityRule actual) {
        assertThat(actual)
            .as("Verify AvailabilityRule relevant properties")
            .satisfies(a -> assertThat(a.getWeekday()).as("check weekday").isEqualTo(expected.getWeekday()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getSlotMinutes()).as("check slotMinutes").isEqualTo(expected.getSlotMinutes()))
            .satisfies(a -> assertThat(a.getValidFrom()).as("check validFrom").isEqualTo(expected.getValidFrom()))
            .satisfies(a -> assertThat(a.getValidUntil()).as("check validUntil").isEqualTo(expected.getValidUntil()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAvailabilityRuleUpdatableRelationshipsEquals(AvailabilityRule expected, AvailabilityRule actual) {
        assertThat(actual)
            .as("Verify AvailabilityRule relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
