package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FavouriteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavouriteAllPropertiesEquals(Favourite expected, Favourite actual) {
        assertFavouriteAutoGeneratedPropertiesEquals(expected, actual);
        assertFavouriteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavouriteAllUpdatablePropertiesEquals(Favourite expected, Favourite actual) {
        assertFavouriteUpdatableFieldsEquals(expected, actual);
        assertFavouriteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavouriteAutoGeneratedPropertiesEquals(Favourite expected, Favourite actual) {
        assertThat(actual)
            .as("Verify Favourite auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavouriteUpdatableFieldsEquals(Favourite expected, Favourite actual) {
        assertThat(actual)
            .as("Verify Favourite relevant properties")
            .satisfies(a -> assertThat(a.getCustomerLogin()).as("check customerLogin").isEqualTo(expected.getCustomerLogin()))
            .satisfies(a -> assertThat(a.getProfessionalRef()).as("check professionalRef").isEqualTo(expected.getProfessionalRef()))
            .satisfies(a -> assertThat(a.getAddedAt()).as("check addedAt").isEqualTo(expected.getAddedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavouriteUpdatableRelationshipsEquals(Favourite expected, Favourite actual) {
        // empty method
    }
}
