package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HighlightAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHighlightAllPropertiesEquals(Highlight expected, Highlight actual) {
        assertHighlightAutoGeneratedPropertiesEquals(expected, actual);
        assertHighlightAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHighlightAllUpdatablePropertiesEquals(Highlight expected, Highlight actual) {
        assertHighlightUpdatableFieldsEquals(expected, actual);
        assertHighlightUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHighlightAutoGeneratedPropertiesEquals(Highlight expected, Highlight actual) {
        assertThat(actual)
            .as("Verify Highlight auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHighlightUpdatableFieldsEquals(Highlight expected, Highlight actual) {
        assertThat(actual)
            .as("Verify Highlight relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHighlightUpdatableRelationshipsEquals(Highlight expected, Highlight actual) {
        assertThat(actual)
            .as("Verify Highlight relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
