package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAllPropertiesEquals(Professional expected, Professional actual) {
        assertProfessionalAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAllUpdatablePropertiesEquals(Professional expected, Professional actual) {
        assertProfessionalUpdatableFieldsEquals(expected, actual);
        assertProfessionalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAutoGeneratedPropertiesEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalUpdatableFieldsEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getUserLogin()).as("check userLogin").isEqualTo(expected.getUserLogin()))
            .satisfies(a -> assertThat(a.getDisplayName()).as("check displayName").isEqualTo(expected.getDisplayName()))
            .satisfies(a -> assertThat(a.getInitials()).as("check initials").isEqualTo(expected.getInitials()))
            .satisfies(a -> assertThat(a.getHeadline()).as("check headline").isEqualTo(expected.getHeadline()))
            .satisfies(a -> assertThat(a.getSpeciality()).as("check speciality").isEqualTo(expected.getSpeciality()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getCountryCode()).as("check countryCode").isEqualTo(expected.getCountryCode()))
            .satisfies(a -> assertThat(a.getYearsPractising()).as("check yearsPractising").isEqualTo(expected.getYearsPractising()))
            .satisfies(a -> assertThat(a.getVerification()).as("check verification").isEqualTo(expected.getVerification()))
            .satisfies(a -> assertThat(a.getInsured()).as("check insured").isEqualTo(expected.getInsured()))
            .satisfies(a -> assertThat(a.getPoliceClearance()).as("check policeClearance").isEqualTo(expected.getPoliceClearance()))
            .satisfies(a -> assertThat(a.getResponseMinutes()).as("check responseMinutes").isEqualTo(expected.getResponseMinutes()))
            .satisfies(a -> assertThat(a.getRebookRatePct()).as("check rebookRatePct").isEqualTo(expected.getRebookRatePct()))
            .satisfies(a -> assertThat(a.getBio()).as("check bio").isEqualTo(expected.getBio()))
            .satisfies(a -> assertThat(a.getLanguages()).as("check languages").isEqualTo(expected.getLanguages()))
            .satisfies(a -> assertThat(a.getDeliveryModes()).as("check deliveryModes").isEqualTo(expected.getDeliveryModes()))
            .satisfies(a ->
                assertThat(a.getAvatarGradientFrom()).as("check avatarGradientFrom").isEqualTo(expected.getAvatarGradientFrom())
            )
            .satisfies(a -> assertThat(a.getAvatarGradientTo()).as("check avatarGradientTo").isEqualTo(expected.getAvatarGradientTo()))
            .satisfies(a -> assertThat(a.getPublishedAt()).as("check publishedAt").isEqualTo(expected.getPublishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalUpdatableRelationshipsEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
