package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceOfferingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceOfferingAllPropertiesEquals(ServiceOffering expected, ServiceOffering actual) {
        assertServiceOfferingAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceOfferingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceOfferingAllUpdatablePropertiesEquals(ServiceOffering expected, ServiceOffering actual) {
        assertServiceOfferingUpdatableFieldsEquals(expected, actual);
        assertServiceOfferingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceOfferingAutoGeneratedPropertiesEquals(ServiceOffering expected, ServiceOffering actual) {
        assertThat(actual)
            .as("Verify ServiceOffering auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceOfferingUpdatableFieldsEquals(ServiceOffering expected, ServiceOffering actual) {
        assertThat(actual)
            .as("Verify ServiceOffering relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getPriceMinor()).as("check priceMinor").isEqualTo(expected.getPriceMinor()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceOfferingUpdatableRelationshipsEquals(ServiceOffering expected, ServiceOffering actual) {
        assertThat(actual)
            .as("Verify ServiceOffering relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
