package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VerificationReviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationReviewAllPropertiesEquals(VerificationReview expected, VerificationReview actual) {
        assertVerificationReviewAutoGeneratedPropertiesEquals(expected, actual);
        assertVerificationReviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationReviewAllUpdatablePropertiesEquals(VerificationReview expected, VerificationReview actual) {
        assertVerificationReviewUpdatableFieldsEquals(expected, actual);
        assertVerificationReviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationReviewAutoGeneratedPropertiesEquals(VerificationReview expected, VerificationReview actual) {
        assertThat(actual)
            .as("Verify VerificationReview auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationReviewUpdatableFieldsEquals(VerificationReview expected, VerificationReview actual) {
        assertThat(actual)
            .as("Verify VerificationReview relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDecision()).as("check decision").isEqualTo(expected.getDecision()))
            .satisfies(a -> assertThat(a.getReviewer()).as("check reviewer").isEqualTo(expected.getReviewer()))
            .satisfies(a -> assertThat(a.getReviewedAt()).as("check reviewedAt").isEqualTo(expected.getReviewedAt()))
            .satisfies(a -> assertThat(a.getEvidenceRef()).as("check evidenceRef").isEqualTo(expected.getEvidenceRef()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationReviewUpdatableRelationshipsEquals(VerificationReview expected, VerificationReview actual) {
        assertThat(actual)
            .as("Verify VerificationReview relationships")
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
