# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: healthconnectPayout
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ODg1NTAwNGRlYjFlMTEwMjY5NzY2OTIzNGNmNmMxNWE2ODcxMGVmOGNiZTM5N2I2ZTg3ODliY2RlYTM0Y2E3N2QyOTA0MGMwMzc3MTNjMWQ2ZmQxYmQyOWZjOTZjZjcwNDdkNmFjMGRiOTRiNjI2MDRiODNhYjVhMmNlNzFlYzI=
