configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODg1NTAwNGRlYjFlMTEwMjY5NzY2OTIzNGNmNmMxNWE2ODcxMGVmOGNiZTM5N2I2ZTg3ODliY2RlYTM0Y2E3N2QyOTA0MGMwMzc3MTNjMWQ2ZmQxYmQyOWZjOTZjZjcwNDdkNmFjMGRiOTRiNjI2MDRiODNhYjVhMmNlNzFlYzI=
