package net.jojoaddison.domain;

import static net.jojoaddison.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BrokerageConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerageConfigAllPropertiesEquals(BrokerageConfig expected, BrokerageConfig actual) {
        assertBrokerageConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertBrokerageConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerageConfigAllUpdatablePropertiesEquals(BrokerageConfig expected, BrokerageConfig actual) {
        assertBrokerageConfigUpdatableFieldsEquals(expected, actual);
        assertBrokerageConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerageConfigAutoGeneratedPropertiesEquals(BrokerageConfig expected, BrokerageConfig actual) {
        assertThat(actual)
            .as("Verify BrokerageConfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerageConfigUpdatableFieldsEquals(BrokerageConfig expected, BrokerageConfig actual) {
        assertThat(actual)
            .as("Verify BrokerageConfig relevant properties")
            .satisfies(a ->
                assertThat(a.getCommissionRate())
                    .as("check commissionRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCommissionRate())
            )
            .satisfies(a -> assertThat(a.getPayoutLagDays()).as("check payoutLagDays").isEqualTo(expected.getPayoutLagDays()))
            .satisfies(a ->
                assertThat(a.getFreeCancellationHours()).as("check freeCancellationHours").isEqualTo(expected.getFreeCancellationHours())
            )
            .satisfies(a ->
                assertThat(a.getLateCancellationPct())
                    .as("check lateCancellationPct")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getLateCancellationPct())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getEffectiveFrom()).as("check effectiveFrom").isEqualTo(expected.getEffectiveFrom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerageConfigUpdatableRelationshipsEquals(BrokerageConfig expected, BrokerageConfig actual) {
        // empty method
    }
}
