package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LedgerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerAllPropertiesEquals(Ledger expected, Ledger actual) {
        assertLedgerAutoGeneratedPropertiesEquals(expected, actual);
        assertLedgerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerAllUpdatablePropertiesEquals(Ledger expected, Ledger actual) {
        assertLedgerUpdatableFieldsEquals(expected, actual);
        assertLedgerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerAutoGeneratedPropertiesEquals(Ledger expected, Ledger actual) {
        assertThat(actual)
            .as("Verify Ledger auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerUpdatableFieldsEquals(Ledger expected, Ledger actual) {
        assertThat(actual)
            .as("Verify Ledger relevant properties")
            .satisfies(a -> assertThat(a.getBookingReference()).as("check bookingReference").isEqualTo(expected.getBookingReference()))
            .satisfies(a -> assertThat(a.getProfessionalRef()).as("check professionalRef").isEqualTo(expected.getProfessionalRef()))
            .satisfies(a -> assertThat(a.getProfessionalLogin()).as("check professionalLogin").isEqualTo(expected.getProfessionalLogin()))
            .satisfies(a -> assertThat(a.getGrossMinor()).as("check grossMinor").isEqualTo(expected.getGrossMinor()))
            .satisfies(a -> assertThat(a.getCommissionMinor()).as("check commissionMinor").isEqualTo(expected.getCommissionMinor()))
            .satisfies(a -> assertThat(a.getNetMinor()).as("check netMinor").isEqualTo(expected.getNetMinor()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getDeliveryMode()).as("check deliveryMode").isEqualTo(expected.getDeliveryMode()))
            .satisfies(a -> assertThat(a.getServiceRef()).as("check serviceRef").isEqualTo(expected.getServiceRef()))
            .satisfies(a -> assertThat(a.getServiceName()).as("check serviceName").isEqualTo(expected.getServiceName()))
            .satisfies(a -> assertThat(a.getEarnedOn()).as("check earnedOn").isEqualTo(expected.getEarnedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerUpdatableRelationshipsEquals(Ledger expected, Ledger actual) {
        assertThat(actual)
            .as("Verify Ledger relationships")
            .satisfies(a -> assertThat(a.getPayout()).as("check payout").isEqualTo(expected.getPayout()));
    }
}
