package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PayoutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutAllPropertiesEquals(Payout expected, Payout actual) {
        assertPayoutAutoGeneratedPropertiesEquals(expected, actual);
        assertPayoutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutAllUpdatablePropertiesEquals(Payout expected, Payout actual) {
        assertPayoutUpdatableFieldsEquals(expected, actual);
        assertPayoutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutAutoGeneratedPropertiesEquals(Payout expected, Payout actual) {
        assertThat(actual)
            .as("Verify Payout auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutUpdatableFieldsEquals(Payout expected, Payout actual) {
        assertThat(actual)
            .as("Verify Payout relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getProfessionalRef()).as("check professionalRef").isEqualTo(expected.getProfessionalRef()))
            .satisfies(a -> assertThat(a.getPeriodStart()).as("check periodStart").isEqualTo(expected.getPeriodStart()))
            .satisfies(a -> assertThat(a.getPeriodEnd()).as("check periodEnd").isEqualTo(expected.getPeriodEnd()))
            .satisfies(a -> assertThat(a.getGrossMinor()).as("check grossMinor").isEqualTo(expected.getGrossMinor()))
            .satisfies(a -> assertThat(a.getCommissionMinor()).as("check commissionMinor").isEqualTo(expected.getCommissionMinor()))
            .satisfies(a -> assertThat(a.getNetMinor()).as("check netMinor").isEqualTo(expected.getNetMinor()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getSettledOn()).as("check settledOn").isEqualTo(expected.getSettledOn()))
            .satisfies(a -> assertThat(a.getBankReference()).as("check bankReference").isEqualTo(expected.getBankReference()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutUpdatableRelationshipsEquals(Payout expected, Payout actual) {
        // empty method
    }
}
